name: Push Daily Single Image Calendar

on:
  schedule:
    - cron: '50 23 * * *' # 每天北京时间 7:50 运行
  workflow_dispatch: # 允许手动触发

jobs:

  push_dxl:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1' # 根据您的需求调整 PHP 版本
        
    - name: Get DXL Image
      run: |
          php dxl.php > dxl.jpg
          ls

    - name: Get Current Date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      
    - name: Upload DXL Image to Telegram
      run: |
        curl -X POST \
          -H 'Content-Type: multipart/form-data' \
          -F "photo=@dxl.jpg" \
          -F "chat_id=${{ secrets.TELEGRAM_TO }}" \
          -F "caption=#今日单向历 ${{ steps.date.outputs.date }}" \
          -F "parse_mode=markdown" \
          https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendPhoto
